server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: silServer
    profiles:
      active: dev
  #  profiles.active: real  # run configuration 에서 local주입해서 사용

  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1

  jpa:
    open-in-view: false        # 트랜잭션 밖 Lazy 로딩 방지
    show-sql: false            # Hibernate SQL 로그 비활성화
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hbm2ddl.auto: create   # create / update / validate / none 중 선택 (postgresql 은 드랍안된다)
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true

  jwt:
    #    secret: ENC(p+UGISqjN1rTvSRsmxNLIM4v1EELgzL6Lw7H4+LCJT7q5zIdLcohcX8xUjycwcH7PGcZi3lpfuZBzt8elTwJMQ4hzhsAwf1r)   # 토큰 암호화 보안키
    secret: ThisIsSeowonFrameworkAndThisFrameworkIsBorn20250101ByDev3   # 토큰 암호화 보안키
    access:
      expiration: 86400	# access토큰 만료시간( )second)
    refresh:
      expiration: 86400	# refresh토큰 만료시간(second)

  messages:
    basename: messages/messages,messages/validations,org.hibernate.validator.ValidationMessages
    encoding: UTF-8

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

logging:
  file:
    path: /Users/Shared/app/silserver/logs

custom:
  url:
    signin: /api/auth/signin  # 로그인url 설정
  swagger:
    url: http://localhost:8080

  dateFormat:
    date: yyyy-MM-dd
    dateStr: yyyyMMdd
    datetime: yyyy-MM-dd HH:mm:ss
    datetimeStr: yyyyMMddHHmmss
    kor: yyyy년 MM월 dd일 a hh시 mm분 ss초

  # 파일암호화
  jasypt:
    encryptor:
      key: sangsil

  file:
    board:
      dir: /Users/Shared/app/silServer/upload
      path: board